/**
 * Generate `src/shared/katexInline.ts` from the installed KaTeX package.
 *
 * The exported authoring page must render maths the way the player does, in
 * every browser it might be opened in — the author's, the editor's offscreen
 * iframe, the headless compile window — with no network and no reachable
 * node_modules. So the library, its stylesheet and its fonts are baked into
 * one importable string: fonts become data: URIs, and only the woff2 sources
 * are kept (every browser the page can meet reads woff2, and the ttf/woff
 * fallbacks would triple the size for nothing).
 *
 * Run `npm run build:katex` after upgrading the katex dependency.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const require = createRequire(import.meta.url);
const dist = dirname(require.resolve('katex/dist/katex.min.css'));

const js = readFileSync(join(dist, 'katex.min.js'), 'utf8');
const autoRender = readFileSync(join(dist, 'contrib/auto-render.min.js'), 'utf8');
const rawCss = readFileSync(join(dist, 'katex.min.css'), 'utf8');

// Keep only the woff2 alternative in each src list, then inline it.
const css = rawCss
  .replace(/src:[^;}]+/g, (src) => {
    const woff2 = src.match(/url\(([^)]*\.woff2)\)\s*format\("woff2"\)/);
    return woff2 ? `src:url(${woff2[1]}) format("woff2")` : src;
  })
  .replace(/url\((fonts\/[^)]*\.woff2)\)/g, (_, path) => {
    const data = readFileSync(join(dist, path)).toString('base64');
    return `url(data:font/woff2;base64,${data})`;
  });

const header = `/**
 * GENERATED by scripts/build-katex-inline.mts — do not edit.
 *
 * KaTeX ${require('katex/package.json').version as string}, inlined for the exported authoring page: the page
 * must look like the slide in any browser, offline, so the library travels
 * inside it. Fonts are data: URIs (woff2 only); see the generator for why.
 */
`;

const escapeForTemplate = (text: string): string =>
  text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const out = `${header}
export const KATEX_JS = \`${escapeForTemplate(js)}\`;

export const KATEX_AUTO_RENDER_JS = \`${escapeForTemplate(autoRender)}\`;

export const KATEX_CSS = \`${escapeForTemplate(css)}\`;
`;

const target = join(dirname(fileURLToPath(import.meta.url)), '../src/shared/katexInline.ts');
writeFileSync(target, out, 'utf8');
console.log(`wrote ${target} (${(out.length / 1024).toFixed(0)} KB)`);
